import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { listResumeReports, ResumeReport } from "../lib/resumeReports";
import { aiPercentOf, getLlmUsageSummary } from "../lib/resume";
import { downloadResumeReportPdf } from "../lib/resumeReportPdf";
import { friendlyError } from "../lib/errors";
import AssessmentDetail from "../components/AssessmentDetail";
import Modal from "../components/Modal";
import LlmUsagePanel from "../components/LlmUsagePanel";
import Pagination, { usePagination } from "../components/Pagination";

const fmtCost = (n?: number) => (n && n > 0 ? `$${n < 1 ? n.toFixed(4) : n.toFixed(2)}` : "—");
const fmtTok = (n?: number) => (n && n > 0 ? n.toLocaleString() : "—");

export default function ResumeReports() {
  const [selected, setSelected] = useState<ResumeReport | null>(null);
  const [searchParams, setSearchParams] = useSearchParams();

  const reportsQ = useQuery({ queryKey: ["resumeReports"], queryFn: () => listResumeReports() });
  const usageQ = useQuery({ queryKey: ["llmUsageSummary"], queryFn: () => getLlmUsageSummary() });

  const reports = reportsQ.data ?? [];
  const { page, setPage, pageCount, pageItems, pageSize, total, startIndex } = usePagination(reports, 25);

  // Auto-open a report when arriving via ?open=<id>.
  useEffect(() => {
    const openId = searchParams.get("open");
    if (openId && reports.length) {
      const match = reports.find((r) => r.id === openId);
      if (match) setSelected(match);
      searchParams.delete("open");
      setSearchParams(searchParams, { replace: true });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reports]);

  const error = reportsQ.error ? friendlyError(reportsQ.error) : null;
  const ratingPill = (rating: string) => (rating === "Strong" ? "green" : rating === "Weak" ? "red" : "amber");
  const aiPill = (v: string) => (v === "Low" ? "green" : v === "High" ? "red" : "amber");

  const refresh = () => {
    reportsQ.refetch();
    usageQ.refetch();
  };

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-end", flexWrap: "wrap", gap: "0.5rem" }}>
        <div>
          <h1>Resume Reports</h1>
          <p className="muted" style={{ marginTop: "-0.25rem" }}>
            Every resume assessment you&#39;ve generated. Click a row to view details, or download a PDF.
          </p>
        </div>
        <button className="btn secondary" onClick={refresh} disabled={reportsQ.isFetching}>
          {reportsQ.isFetching ? <span className="spinner dark" /> : "⟳"} Refresh
        </button>
      </div>

      {error && <div className="alert error">{error}</div>}

      <LlmUsagePanel summary={usageQ.data} />

      <div className="card">
        {reportsQ.isLoading ? (
          <div className="center-load" style={{ minHeight: "30vh" }}>
            <div className="spinner dark" />
          </div>
        ) : reports.length > 0 ? (
          <>
            <div className="table-wrap">
              <table className="data">
                <thead>
                  <tr>
                    <th style={{ width: 44 }}>#</th>
                    <th>Date</th>
                    <th>Generated by</th>
                    <th>Candidate</th>
                    <th>Fit</th>
                    <th>Rating</th>
                    <th>AI-generated</th>
                    <th>Model</th>
                    <th style={{ textAlign: "right" }}>Tokens</th>
                    <th style={{ textAlign: "right" }}>Est. cost</th>
                    <th>Report</th>
                  </tr>
                </thead>
                <tbody>
                  {pageItems.map((r, i) => (
                    <tr key={r.id} style={{ cursor: "pointer" }} onClick={() => setSelected(r)}>
                      <td className="muted">{startIndex + i + 1}</td>
                      <td>{r.createdAt ? new Date(r.createdAt).toLocaleString() : "—"}</td>
                      <td className="muted" style={{ whiteSpace: "normal", fontSize: "0.82rem" }} title={r.createdByEmail || ""}>
                        {r.createdByName || "—"}
                      </td>
                      <td style={{ whiteSpace: "normal", fontWeight: 600 }}>{r.candidateName || "—"}</td>
                      <td>{Math.round(Number(r.fitScore) || 0)}</td>
                      <td><span className={`pill ${ratingPill(r.rating)}`}>{r.rating}</span></td>
                      <td>
                        {(() => {
                          const p = aiPercentOf(r);
                          const cls = p != null ? (p > 65 ? "red" : p >= 30 ? "amber" : "green") : aiPill(r.aiGeneratedLikelihood);
                          return <span className={`pill ${cls}`}>{p != null ? `${p}%` : r.aiGeneratedLikelihood}</span>;
                        })()}
                      </td>
                      <td className="muted" style={{ fontSize: "0.8rem" }}>{r.provider} / {r.model}</td>
                      <td style={{ textAlign: "right" }}>{fmtTok(r.totalTokens)}</td>
                      <td style={{ textAlign: "right" }}>{fmtCost(r.cost)}</td>
                      <td onClick={(e) => e.stopPropagation()}>
                        <button
                          className="btn secondary"
                          style={{ padding: "0.35rem 0.7rem" }}
                          onClick={() => downloadResumeReportPdf(r)}
                        >
                          ⬇ PDF
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            <Pagination page={page} pageCount={pageCount} total={total} pageSize={pageSize} onPage={setPage} />
          </>
        ) : (
          <div style={{ textAlign: "center", padding: "2rem", color: "var(--muted)" }}>
            <p>No resume reports yet.</p>
            <p style={{ fontSize: "0.9rem" }}>
              Run an assessment on the <Link to="/resume">Resume Parsing</Link> tab and it will appear here.
            </p>
          </div>
        )}
      </div>

      <Modal
        open={!!selected}
        onClose={() => setSelected(null)}
        title={selected?.candidateName || "Resume report"}
        footer={
          <>
            <button className="btn ghost" onClick={() => setSelected(null)}>Close</button>
            {selected && (
              <button className="btn" onClick={() => downloadResumeReportPdf(selected)}>
                ⬇ Download PDF
              </button>
            )}
          </>
        }
      >
        {selected && (
          <>
            <p className="muted" style={{ fontSize: "0.82rem", marginTop: 0 }}>
              {selected.createdAt ? new Date(selected.createdAt).toLocaleString() : "—"}
              {selected.createdByName ? ` · by ${selected.createdByName}` : ""} · {selected.provider} / {selected.model}
              {(selected.totalTokens ?? 0) > 0 && (
                <>
                  {" · "}
                  {fmtTok(selected.promptTokens)} in + {fmtTok(selected.completionTokens)} out ={" "}
                  {fmtTok(selected.totalTokens)} tokens · Est. cost {fmtCost(selected.cost)}
                </>
              )}
            </p>
            <AssessmentDetail a={selected} />
          </>
        )}
      </Modal>
    </div>
  );
}
